# RTSP Module Makefile
# This file is included by the main Makefile when ENABLE_RTSP=1
# Copyright (C) 2025 Paul Philippov, Thingino Project

# RTSP module object files
RTSP_OBJECTS = obj/modules/rtsp/rtsp_module.o \
               obj/modules/rtsp/rtsp_server.o \
               obj/modules/rtsp/rtsp_consumer.o

# Add RTSP module objects to the main build
OBJS += $(RTSP_OBJECTS)

# RTSP module compilation rules
obj/modules/rtsp/rtsp_module.o: src/modules/rtsp/rtsp_module.c src/modules/rtsp/rtsp_module.h
	@mkdir -p obj/modules/rtsp
	$(CC) $(CFLAGS) \
		-I$(LIBIMP_INC_DIR) \
		-I$(LIBIMP_INC_DIR)/imp \
		-I$(LIBIMP_INC_DIR)/sysutils \
		-I./include \
		-I./src \
		-isystem $(THIRDPARTY_INC_DIR) \
		-c $< -o $@

obj/modules/rtsp/rtsp_server.o: src/modules/rtsp/rtsp_server.c src/modules/rtsp/rtsp_server.h
	@mkdir -p obj/modules/rtsp
	$(CC) $(CFLAGS) \
		-I$(LIBIMP_INC_DIR) \
		-I$(LIBIMP_INC_DIR)/imp \
		-I$(LIBIMP_INC_DIR)/sysutils \
		-I./include \
		-I./src \
		-isystem $(THIRDPARTY_INC_DIR) \
		-c $< -o $@

obj/modules/rtsp/rtsp_consumer.o: src/modules/rtsp/rtsp_consumer.c src/modules/rtsp/rtsp_consumer.h
	@mkdir -p obj/modules/rtsp
	$(CC) $(CFLAGS) \
		-I$(LIBIMP_INC_DIR) \
		-I$(LIBIMP_INC_DIR)/imp \
		-I$(LIBIMP_INC_DIR)/sysutils \
		-I./include \
		-I./src \
		-isystem $(THIRDPARTY_INC_DIR) \
		-c $< -o $@

# Clean rule for RTSP module
clean-rtsp:
	rm -f $(RTSP_OBJECTS)

.PHONY: clean-rtsp
